### ISSUE TITLE
Divide by 0 panic computing objective value

### ISSUE THREAD

**Issue by nlordell** [gnosis/gp-v2-services#420]
We encountered the following panic computing the objective value:
```
ERROR (pod: dev-dfusion-v2-solver-rinkeby-85d5b74797-mvvmk):
2021-03-26T15:05:43.197Z ERROR shared::tracing: thread 'main' panicked at 'attempt to divide by zero', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/num-bigint-0.4.0/src/biguint/division.rs:160:9:
  0: std::panicking::begin_panic
  1: num_bigint::biguint::division::div_rem_ref
  2: num_bigint::bigint::division::<impl core::ops::arith::Div for num_bigint::bigint::BigInt>::div
  3: <num_rational::Ratio<T> as core::ops::arith::Div>::div
  4: solver::settlement::Settlement::objective_value
  5: solver::driver::Driver::single_run::{{closure}}
  6: solver::main::{{closure}}
  7: tokio::runtime::enter::Enter::block_on
  8: tokio::runtime::thread_pool::ThreadPool::block_on
  9: tokio::runtime::context::enter
 10: tokio::runtime::handle::Handle::enter
 11: solver::main
```

**Comment by marcovc** [comment]
I suppose we don't have the example that caused this, right?

**Comment by nlordell** [comment]
I'm not sure where to look for it :see_no_evil:

**Comment by marcovc** [comment]
It appears there is no division on function #4 in the "stack trace" above. Could it be that the code is inlined due to compiler optimizations?

**Comment by vkgnosis** [comment]
There are divisions in the functions objective_value calls so that's probably it. Although I am surprised that we don't get line numbers here. Will investigate.

**Comment by marcovc** [comment]
> There are divisions in the functions objective_value calls so that's probably it. 

But if the division is happening from a function called by the objective_value, I was expecting that that function is also part of the stack trace. Unless it got inlined by the compiler or something.

**Comment by vkgnosis** [comment]
Yes, I mean the inlining is probably the cause for that.

**Comment by bh2smith** [comment]
The division occurs in three places from within `objective_value`

1. `buy_order_surplus` here 
http://github.com/gnosis/gp-v2-services/blob/a7cd0ed35f3bfa1954d8e943978da1784224f6f4/solver/src/settlement.rs#L178-L179
2. `sell_order_surplus` here - 
http://github.com/gnosis/gp-v2-services/blob/a7cd0ed35f3bfa1954d8e943978da1784224f6f4/solver/src/settlement.rs#L200-L201
3. `total_surplus` when normalizing
http://github.com/gnosis/gp-v2-services/blob/a7cd0ed35f3bfa1954d8e943978da1784224f6f4/solver/src/settlement.rs#L146-L149

**Comment by marcovc** [comment]
Thanks Ben! I guess then it can only be #3, as there is a guard on the other two.

**Comment by vkgnosis** [comment]
After applying the fix to see panic line numbers we got a new panic:

```
2021-03-30T12:19:05.091Z ERROR shared::tracing: thread 'main' panicked at 'attempt to divide by zero', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/num-bigint-0.4.0/src/biguint/division.rs:160:9:

thread 'main' panicked at 'attempt to divide by zero', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/num-bigint-0.4.0/src/biguint/division.rs:160:9

stack backtrace:

   0: std::panicking::begin_panic

             at ./rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:519:12

   1: num_bigint::biguint::division::div_rem_ref

             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/num-bigint-0.4.0/src/biguint/division.rs:160:9

   2: <num_bigint::biguint::BigUint as num_integer::Integer>::div_rem

             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/num-bigint-0.4.0/src/biguint.rs:186:9

   3: <num_bigint::bigint::BigInt as num_integer::Integer>::div_rem

             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/num-bigint-0.4.0/src/bigint.rs:358:28

   4: num_bigint::bigint::division::<impl core::ops::arith::Div<&num_bigint::bigint::BigInt> for &num_bigint::bigint::BigInt>::div

             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/num-bigint-0.4.0/src/bigint/division.rs:18:22

   5: num_bigint::bigint::division::<impl core::ops::arith::Div<&num_bigint::bigint::BigInt> for num_bigint::bigint::BigInt>::div

             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/num-bigint-0.4.0/src/macros.rs:71:17

   6: num_bigint::bigint::division::<impl core::ops::arith::Div for num_bigint::bigint::BigInt>::div

             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/num-bigint-0.4.0/src/macros.rs:11:17

   7: <num_rational::Ratio<T> as core::ops::arith::Div>::div

             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/num-rational-0.4.0/src/lib.rs:724:13

   8: solver::settlement::Settlement::total_surplus::{{closure}}

             at ./usr/src/oba-services/solver/src/settlement.rs:145:36

   9: core::iter::traits::iterator::Iterator::fold

             at ./rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/iter/traits/iterator.rs:2124:21

  10: solver::settlement::Settlement::total_surplus

             at ./usr/src/oba-services/solver/src/settlement.rs:124:9

  11: solver::settlement::Settlement::objective_value

             at ./usr/src/oba-services/solver/src/settlement.rs:154:15

  12: solver::driver::Driver::single_run::{{closure}}

             at ./usr/src/oba-services/solver/src/driver.rs:161:17

  13: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll

             at ./rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/future/mod.rs:80:19

  14: solver::driver::Driver::run_forever::{{closure}}

             at ./usr/src/oba-services/solver/src/driver.rs:65:19

  15: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll

             at ./rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/future/mod.rs:80:19

  16: solver::main::{{closure}}

             at ./usr/src/oba-services/solver/src/main.rs:147:5

  17: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll

             at ./rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/future/mod.rs:80:19

  18: tokio::runtime::enter::Enter::block_on::{{closure}}

             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.24/src/runtime/enter.rs:160:58

  19: tokio::coop::with_budget::{{closure}}

             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.24/src/coop.rs:127:9

  20: std::thread::local::LocalKey<T>::try_with

             at ./rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/thread/local.rs:272:16

  21: std::thread::local::LocalKey<T>::with

             at ./rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/thread/local.rs:248:9

  22: tokio::coop::with_budget

             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.24/src/coop.rs:120:5

  23: tokio::coop::budget

             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.24/src/coop.rs:96:5

  24: tokio::runtime::enter::Enter::block_on

             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.24/src/runtime/enter.rs:160:35

  25: tokio::runtime::thread_pool::ThreadPool::block_on

             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.24/src/runtime/thread_pool/mod.rs:82:9

  26: tokio::runtime::Runtime::block_on::{{closure}}

             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.24/src/runtime/mod.rs:446:39

  27: tokio::runtime::context::enter

             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.24/src/runtime/context.rs:72:5

  28: tokio::runtime::handle::Handle::enter

             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.24/src/runtime/handle.rs:76:9

  29: tokio::runtime::Runtime::block_on

             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.24/src/runtime/mod.rs:441:9

  30: solver::main

             at ./usr/src/oba-services/solver/src/main.rs:70:1

  31: core::ops::function::FnOnce::call_once

             at ./rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/ops/function.rs:227:5

note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by bh2smith** [comment]
It looks like the panic is coming from the `div_rem` and makes me wonder if there aren't upstream changes that could be made.
